version: '3'

tasks:
  go-mod:
    desc: Tidy Go modules
    cmds:
      - go mod tidy

  go-fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  go-vet:
    desc: Run static analysis
    cmds:
      - go vet ./...

  go-run:
    desc: Build and run the game
    cmds:
      - go run ./cmd/cyberspace

  go-build:
    desc: Build the binary
    cmds:
      - go build -o bin/cyberspace ./cmd/cyberspace

  go-test:
    desc: Run tests
    cmds:
      - go test ./...

  go-lint:
    desc: Run linter
    cmds:
      - golangci-lint run --fix ./...

  sanity:
    desc: Run all checks (fmt, build, test, vet)
    deps:
      - go-mod
      - go-fmt
      - go-vet
      - go-lint
      - go-test
      - go-build
